# Generated by Django 5.1.4 on 2025-01-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default='https://default.com', unique=True),
        ),
    ]
