# Generated by Django 5.1.4 on 2025-01-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
