# Generated by Django 5.1.4 on 2025-04-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='full_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
