# Generated by Django 5.1.4 on 2025-04-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
