# Generated by Django 5.1.4 on 2025-04-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, choices=[('TechCrunch', 'TechCrunch'), ('Engadget', 'Engadget'), ('The Verge', 'The Verge')], max_length=100, null=True),
        ),
    ]
