# Generated by Django 5.1.4 on 2025-04-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=3, max_length=254),
            preserve_default=False,
        ),
    ]
