# Generated by Django 5.1.4 on 2025-04-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='no-reply@gmail.com', max_length=254),
        ),
    ]
